---
version: "3.2"

services:
  tinylist:
    image: 127.0.0.1:5000/tinylist
    environment:
      PROD: 'true'
      DB_URL: http://db
      DB_PORT: 5984
      DB_USER: tinylist
      DB_PASS: tinylist
#      CREATE_DB_URL: http://db:5984
      CREATE_DB_URL: 'http://db:5984'
#      NODE_ENV: development
#      SERVICE_WORKER_FILE: 
    ports:
      - "80:80"
#      - "81:81"
      - "443:443"
    depends_on:
      - db

  db:
    image: couchdb
    environment:
      COUCHDB_USER: tinylist
      COUCHDB_PASSWORD: tinylist
    volumes:
      - /mnt/data/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"


